"""add marks

Revision ID: 4c97930226e1
Revises: ceb47c6d9afe
Create Date: 2023-11-15 17:21:15.242368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c97930226e1'
down_revision: Union[str, None] = 'ceb47c6d9afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marks_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('lesson_number', sa.Integer(), nullable=False),
    sa.Column('mark', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('parcipiant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parcipiant_id'], ['parcipiants_id.parcipiant_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject', 'lesson_number', 'mark', 'date', 'parcipiant_id', name='unique_mark')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks_table')
    # ### end Alembic commands ###
