"""add fields name

Revision ID: 5a52732b4555
Revises: 0d905673ca4c
Create Date: 2023-10-28 18:35:41.903723

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5a52732b4555'
down_revision: Union[str, None] = '0d905673ca4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcipiants_id', sa.Column('name', sa.String(), nullable=True))
    op.add_column('parcipiants_id', sa.Column('grade', sa.String(), nullable=True))
    op.add_column('parcipiants_id', sa.Column('school', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parcipiants_id', 'school')
    op.drop_column('parcipiants_id', 'grade')
    op.drop_column('parcipiants_id', 'name')
    # ### end Alembic commands ###
