"""add marks

Revision ID: 62d2f4b50940
Revises: ceb47c6d9afe
Create Date: 2023-11-17 16:10:07.610694

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '62d2f4b50940'
down_revision: Union[str, None] = 'ceb47c6d9afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marks_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('lesson_number', sa.Integer(), nullable=False),
    sa.Column('mark', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('parcipiant_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parcipiant_id'], ['parcipiants_id.parcipiant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks_table')
    # ### end Alembic commands ###
